# Generated by Django 6.1 on 2026-09-04 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.lesson",
            ),
        ),
    ]
